pool:
  vmImage: ubuntu-latest
steps:
  - task: InstallMATLAB@0
  - task: RunMATLABTests@0
    inputs:
      sourceFolder: matlab/OptiProfiler/src
      codeCoverageCobertura: coverage.xml
  - script: bash <(curl -s https://codecov.io/bash)