[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "OptiProfiler"
description = "Benchmarking optimization solvers using performance and data profiles"
readme = "README.rst"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Cunxin Huang", email = "cun-xin.huang@connect.polyu.hk"},
    {name = "Tom M. Ragonneau", email = "tom.ragonneau@polyu.edu.hk"},
    {name = "Zaikun Zhang", email = "zaikun.zhang@polyu.edu.hk"},
]
maintainers = [
    {name = "Cunxin Huang", email = "cun-xin.huang@connect.polyu.hk"},
    {name = "Tom M. Ragonneau", email = "tom.ragonneau@polyu.edu.hk"},
    {name = "Zaikun Zhang", email = "zaikun.zhang@polyu.edu.hk"},
]
keywords = []
classifiers = []
dependencies = [
    "numpy",
]
dynamic = ["version"]

[project.optional-dependencies]
doc = [
    "numpydoc==1.5.0",
    "Sphinx==7.2.5",
    "sphinx-copybutton==0.5.2",
    "sphinx-rtd-theme==1.3.0",
]

[tool.setuptools.dynamic]
version = {attr = "OptiProfiler.__version__"}

[tool.setuptools.packages.find]
where = ["python"]
include = ["OptiProfiler*"]
