"""
Trusted H5 reader: generic ``_pickled`` fields written by earlier versions may
contain ``optiprofiler.utils.FeatureOption`` members, including the removed
``n_runs`` member. They must decode through the trusted compatibility decoder
at both H5 branches (top-level and nested) before any post-load remapping can
run; a plain ``pickle.loads`` fails inside the enum constructor.

The embedded bytes are the genuine ac4 native-serialization fixture
``enum-key-and-value.pkl`` (sha256 be4aa8b7…) generated by the clean ac4a67e
source before ``FeatureOption.N_RUNS`` was removed. This is a serialization
compatibility gate, not a safety guarantee for untrusted pickle payloads.
"""

import base64
import hashlib
import pickle

import h5py
import numpy as np
import pytest

from optiprofiler.loader import load_results_from_h5

ENUM_KEY_AND_VALUE = base64.b64decode(
    'gASVSgAAAAAAAAB9lCiMEm9wdGlwcm9maWxlci51dGlsc5SMDUZlYXR1cmVPcHRpb26Uk5SMBm5fcnVuc5SFlFKUSwOMCmVu'
    'dW1fdmFsdWWUaAZ1Lg==')
ENUM_KEY_AND_VALUE_SHA256 = 'be4aa8b7cfc0bd2823a0420c1813ed98e0db9b2348a4f6334a8b5dab5a521ffe'


def write_enum_fields_archive(path):
    """Mirror the genuine ``enum-fields.h5`` layout: top-level and nested pickled enum fields."""
    with h5py.File(path, 'w') as archive:
        group = archive.create_group('plib_0')
        group.create_dataset('plib', data='native_serialization_fixture')
        group.create_dataset('numerical_control', data=np.array([1.25, -2.5, np.inf, np.nan]))
        group.create_dataset('plib_options_pickled', data=np.void(ENUM_KEY_AND_VALUE))
        nested = group.create_group('nested')
        nested.create_dataset('enum_options_pickled', data=np.void(ENUM_KEY_AND_VALUE))


def test_fixture_bytes_are_the_frozen_ac4_pickle():
    assert hashlib.sha256(ENUM_KEY_AND_VALUE).hexdigest() == ENUM_KEY_AND_VALUE_SHA256
    # Documents why a boundary decoder exists: the active enum no longer has the member.
    with pytest.raises(ValueError, match="'n_runs' is not a valid FeatureOption"):
        pickle.loads(ENUM_KEY_AND_VALUE)


@pytest.mark.parametrize('location', ['top-level', 'nested'])
def test_trusted_old_h5_enum_fields_survive_count_ownership_migration(tmp_path, location):
    path = tmp_path / 'enum-fields.h5'
    write_enum_fields_archive(path)
    original = path.read_bytes()
    results = load_results_from_h5(str(path))
    assert len(results) == 1
    assert results[0]['plib'] == 'native_serialization_fixture'
    options = results[0]['plib_options'] if location == 'top-level' else results[0]['nested']['enum_options']
    # A decoded historical key may be a compatibility value or its string; the
    # value is looked up by its string spelling and the member keeps its value.
    assert options['n_runs'] == 3
    value = options['enum_value']
    assert getattr(value, 'value', value) == 'n_runs'
    np.testing.assert_array_equal(results[0]['numerical_control'], [1.25, -2.5, np.inf, np.nan])
    assert path.read_bytes() == original
