function registration = legacyProblemLibraryRegistration(name)
%LEGACYPROBLEMLIBRARYREGISTRATION preserves the core-local folder contract.
%
% This compatibility fallback is intentionally isolated. New optional
% libraries should use registerProblemLibrary and may live anywhere.

    private_dir = fileparts(mfilename('fullpath'));
    package_root = fullfile(private_dir, '..', '..');
    root = fullfile(package_root, 'problem_libs', name);
    if exist(root, 'dir') ~= 7
        registration = [];
        return
    end
    registration = struct( ...
        'name', name, ...
        'api_version', 1, ...
        'role', 'legacy-local', ...
        'root', root, ...
        'select_function', [name, '_select'], ...
        'load_function', [name, '_load'], ...
        'collect_info_function', '', ...
        'check_available_function', '', ...
        'platforms', {{'linux', 'macos', 'windows'}});
    registration = normalizeProblemLibraryRegistration(registration);
end
