name: test-matlab

on:
  push:
    branches: [matlab]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone MatCUTEst
        uses: actions/checkout@v4.1.1
        with:
          repository: matcutest/matcutest_compiled
          path: matcutest

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      - name: Run tests
        uses: matlab-actions/run-command@v1.2.3
        with:
          command: |
            root_dir = pwd();

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest')); install(); cd(root_dir);

            % Check the installation
            help matcutest, which('macup'), which('decup'), which('secup')

      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Run MATLAB Tests
        uses: matlab-actions/run-tests@v0
        with:
          source-folder: 'matlab/OptiProfiler/src'
          code-coverage-cobertura: 'coverage.xml'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml