name: test-matlab

on:
  push:
    branches: [matlab]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone MatCUTEst
        uses: actions/checkout@v4
        with:
          repository: matcutest/matcutest_compiled
          path: matcutest
      - uses: actions/checkout@v2
      - uses: matlab-actions/setup-matlab@v0
      - uses: matlab-actions/run-tests@v0
        with:
          source-folder: matlab/OptiProfiler/src
          code-coverage-cobertura: coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.xml