name: test-matlab

on:
  push:
    branches: [matlab]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone MatCUTEst
        uses: actions/checkout@v4
        with:
          repository: matcutest/matcutest_compiled
          path: matcutest
      - uses: actions/checkout@v2
      - uses: matlab-actions/setup-matlab@v0
      - name: Install MatCUTEst
        uses: matlab-actions/run-command@v1.2.3
        with:
          command: |
            root_dir = pwd();

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest')); install(); cd(root_dir);

            % Check the installation
            help matcutest, which('macup'), which('decup'), which('secup')
      - uses: matlab-actions/run-tests@v0
        with:
          source-folder: matlab/OptiProfiler/src
          code-coverage-cobertura: coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.xml